### ISSUE TITLE
How to write items into a collection with partition key?

### ISSUE THREAD

**Issue by romansoft** [joeyboey/node-red-contrib-cosmos-db#1]
Great initiative with this library!

Could you please provide an example on how to write items into a collection with a partition key?

**Comment by joeyboey** [comment]
Right now you can only read data via the SQL-Query API. However you can expose the CosmosClient and CosmosContainer Object on the output. with that you can write data according to the [CosmosClient Documentation](https://docs.microsoft.com/de-de/javascript/api/@azure/cosmos/container?view=azure-node-latest). I would recommend you to check out the docs.
A minimum working example of an upsert operation in a function node would look a little bit like this:

```js
msg.cosmos.items.upsert(user).then(o => {
        node.send(o);
    }).catch(e => {
        node.error(e);
    });
```

For that to work you first got to make a request using the SQL Node. Within you have the option to expose the Cosmos Container Object. With that you can modify essentially the whole database in plain javascript using the aforementioned api.

**Comment by romansoft** [comment]
Thanks, it's working!
